version: '3'
services:
  TIG-influx:
    image: "influxdb:1.8.5"
    user: root
    environment:
      - INFLUXDB_DB=TIGdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Cisc0123
      - INFLUXDB_USER=TIGdbuser
      - INFLUXDB_USER_PASSWORD=Cisc0123
    volumes:
      - /data/influxdb:/var/lib/influxdb
    networks:
      - TIG_net
    ports:
      - "8086:8086"
    restart: always
  TIG-telegraf:
    image: "telegraf"
    user: root
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - TIG_net
    ports:
      - "57000:57000"
    depends_on:
      - "TIG-influx"
    restart: always
  TIG-grafana:
    image: "grafana/grafana"
    user: root
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./TIG.project.com.key:/etc/grafana/TIG.project.com.key
      - ./TIG.project.com.cer:/etc/grafana/TIG.project.com.cer
      - ./ldap.toml:/etc/grafana/ldap.toml
    networks:
      - TIG_net
    ports:
      - "3000:3000"
    depends_on:
      - "TIG-influx"
    restart: always

networks:
  TIG_net:
    driver: bridge
