[[servers]]
host = "10.1.1.100"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "project\\%s"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=project,dc=com"]

[servers.attributes]
member_of = "memberOf"
email =  "mail"

# [[servers.group_mappings]] omitted for clarity